/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-05-09 05:48:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/customer/commons/top.jsp", Long.valueOf(1462766049713L));
    _jspx_dependants.put("/customer/commons/foot.jsp", Long.valueOf(1462766049703L));
    _jspx_dependants.put("/customer/commons/head.jsp", Long.valueOf(1462767449966L));
    _jspx_dependants.put("/commons/taglibs.jsp", Long.valueOf(1458966020987L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title>IBooK-商家服务平台</title>\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n");
      out.write("\t\t<meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t\t<meta content=\"\" name=\"description\">\r\n");
      out.write("\t\t<meta content=\"bin--开发\" name=\"author\">\r\n");
      out.write("<!-- BEGIN PACE PLUGIN FILES -->\r\n");
      out.write("<link href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("' rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<link href='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("' rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<!-- cart -->\r\n");
      out.write("<script src='");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<!-- cart -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href='");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("<!-- for bootstrap working -->\r\n");
      out.write("<script type=\"text/javascript\" src='");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("<link href='");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("' rel=\"stylesheet\">\r\n");
      out.write("<script src='");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"header-grid\">\r\n");
      out.write("\t\t\t\t<div class=\"header-grid-left animated wow slideInLeft\"\r\n");
      out.write("\t\t\t\t\tdata-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"glyphicon glyphicon-envelope\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i><a href=\"mailto:info@example.com\">@example.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"glyphicon glyphicon-earphone\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i>+1234 <span>567</span> 892</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><i class=\"glyphicon glyphicon-log-in\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i><a href=\"login.html\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"glyphicon glyphicon-book\" aria-hidden=\"true\"></i><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"register.html\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header-grid-right animated wow slideInRight\"\r\n");
      out.write("\t\t\t\t\tdata-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"social-icons\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"twitter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"g\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logo-nav\">\r\n");
      out.write("\t\t\t\t<div class=\"logo-nav-left animated wow zoomIn\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\">Best Store <span>Shop anywhere</span></a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo-nav-left1\">\r\n");
      out.write("\t\t\t\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-header nav_2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"navbar-toggle collapsed navbar-toggle1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-megadropdown-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Mega Menu -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\">Products <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu multi-column columns-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multi-column-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>Men's Wear</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Clothing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Wallets</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Shoes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Watches</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Accessories</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multi-column-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>Women's Wear</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Clothing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Wallets,Bags</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Footwear</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Watches</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Accessories</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Jewellery</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Beauty & Grooming</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multi-column-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>Kid's Wear</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Kids Home Fashion</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Boy's Clothing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Girl's Clothing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Shoes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"products.html\">Brand Stores</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\">Furniture <b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu multi-column columns-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multi-column-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>Home Collection</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Cookware</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Sofas</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Dining Tables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Shoe Racks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Home Decor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multi-column-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>Office Collection</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Carpets</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Tables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Sofas</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Shoe Racks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Sockets</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Electrical Machines</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"multi-column-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6>Decorations</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Toys</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Wall Clock</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Lighting</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"furniture.html\">Top Brands</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"short-codes.html\">Short Codes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"mail.html\">Mail Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo-nav-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search-box\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"sb-search\" class=\"sb-search\">\r\n");
      out.write("\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"sb-search-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter your search term...\" type=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"search\"> <input class=\"sb-search-submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"submit\" value=\"\"> <span class=\"sb-icon-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- search-scripts -->\r\n");
      out.write("\t\t\t\t\t<script src=\"js/classie.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"js/uisearch.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tnew UISearch(document.getElementById('sb-search'));\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<!-- //search-scripts -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cart box_1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"checkout.html\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"total\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"simpleCart_total\"></span> (<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"simpleCart_quantity\" class=\"simpleCart_quantity\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\titems)\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/bag.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"simpleCart_empty\">Empty Cart</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //header -->");
      out.write("\r\n");
      out.write("<!-- breadcrumbs -->\r\n");
      out.write("\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb breadcrumb1 animated wow slideInLeft\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\"></span>首页</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">图书详情<i class=\"fa fa-save\"></i></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //breadcrumbs -->\r\n");
      out.write("\t\t<!-- single -->\r\n");
      out.write("\t\t<div class=\"single\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 single-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 single-right-left animated wow slideInUp\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li data-thumb=\"images/si.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"thumb-image\"> <img src=\"images/si.jpg\" data-imagezoom=\"true\" class=\"img-responsive\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li data-thumb=\"images/si1.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"thumb-image\"> <img src=\"images/si1.jpg\" data-imagezoom=\"true\" class=\"img-responsive\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li data-thumb=\"images/si2.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"thumb-image\"> <img src=\"images/si2.jpg\" data-imagezoom=\"true\" class=\"img-responsive\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- flixslider -->\r\n");
      out.write("\t\t\t\t\t\t<script defer src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<link rel=\"stylesheet\" href=\"css/flexslider.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t// Can also be used with $(document).ready()\r\n");
      out.write("\t\t\t\t\t\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$('.flexslider').flexslider({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimation: \"slide\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontrolNav: \"thumbnails\"\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<!-- flixslider -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 single-right-left simpleCart_shelfItem animated wow slideInRight\" data-wow-delay=\".5s\" style=\"padding-left: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Men's Solid Casual Shirt 课程</h3>\r\n");
      out.write("\t\t\t\t\t\t<h4><span class=\"item_price\">价格：￥550</span> </h4>\r\n");
      out.write("\t\t\t\t\t\t<h4 style=\"color: black;\">折扣： <span class=\"item_price\" style=\"color: red;\">0.95 折</span> </h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"rating1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"starRating\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"rating5\" type=\"radio\" name=\"rating\" value=\"5\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"rating5\">5</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"rating4\" type=\"radio\" name=\"rating\" value=\"4\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"rating4\">4</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"rating3\" type=\"radio\" name=\"rating\" value=\"3\" checked disabled>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"rating3\">3</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"rating2\" type=\"radio\" name=\"rating\" value=\"2\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"rating2\">2</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"rating1\" type=\"radio\" name=\"rating\" value=\"1\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"rating1\">1</label>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 style=\"font-family: '微软雅黑';\"><i>简介:</i></h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p>作者：李强斌QBB</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>这里是图书Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-quality\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-quality-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"quantity\"> <h5>数量:</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"quantity-select\" >                           \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"entry value-minus\" onclick=\"reduce();\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"entry value\"><input type=\"text\" id=\"number\" name=\"number\" value=\"1\" class=\"form-control small\" style=\"margin-top:-10px;height: 40px;\" /></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"entry value-plus active\" onclick=\"add();\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"occasion-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"item_add\" href=\"#\">加入购物车</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"item_add\" href=\"#\">直接购买</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"bootstrap-tab animated wow slideInUp\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bs-example bs-example-tabs\" role=\"tabpanel\" data-example-id=\"togglable-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"myTab\" class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#home\" id=\"home-tab\" role=\"tab\" data-toggle=\"tab\" aria-controls=\"home\" aria-expanded=\"true\">Description</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"#profile\" role=\"tab\" id=\"profile-tab\" data-toggle=\"tab\" aria-controls=\"profile\">Reviews(2)</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\" class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" id=\"myTabDrop1\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-controls=\"myTabDrop1-contents\">Information <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"myTabDrop1\" id=\"myTabDrop1-contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#dropdown1\" tabindex=\"-1\" role=\"tab\" id=\"dropdown1-tab\" data-toggle=\"tab\" aria-controls=\"dropdown1\">cleanse</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#dropdown2\" tabindex=\"-1\" role=\"tab\" id=\"dropdown2-tab\" data-toggle=\"tab\" aria-controls=\"dropdown2\">fanny</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade in active bootstrap-tab-text\" id=\"home\" aria-labelledby=\"home-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>作者李强斌。。。。。 haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tCosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5>图书简介</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>javaEE Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tCosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade bootstrap-tab-text\" id=\"profile\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grids\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/tupian1.jpg\" alt=\" \" class=\"img-responsive\" style=\"border-radius: 90px;width:80px;height: 80px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">用户1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li style=\"color: gray;\"><div style=\"color: red;margin-right: 50px;\"><i class=\"fa fa-star\"></i><i class=\"fa fa-star-half-empty\"></i><i class=\"fa fa-star-half-o\"></i></div>2016/5/4 20:30:09</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>这本书满分，可以好评</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/tupian3.jpg\" style=\"border-radius: 90px;width:80px;height: 80px;\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Admin</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-share\" aria-hidden=\"true\"></span>Reply</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/tupian4.jpg\" alt=\" \" class=\"img-responsive\"  style=\"border-radius: 90px;width:80px;height: 80px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Admin</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-share\" aria-hidden=\"true\"></span>Reply</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/tupian2.jpg\" alt=\" \"  sstyle=\"border-radius: 90px;width:100px;height: 100px;\"style=\"border-radius: 90px;width:80px;height: 80px;\" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"bootstrap-tab-text-grid-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Admin</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-share\" aria-hidden=\"true\"></span>Reply</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"add-review\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4>add a review</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" value=\"Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Name';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" value=\"Email\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Email';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" value=\"Subject\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Subject';}\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea type=\"text\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Message...';}\" required=\"\">Message...</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Send\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade bootstrap-tab-text\" id=\"dropdown1\" aria-labelledby=\"dropdown1-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbanksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tof them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade bootstrap-tab-text\" id=\"dropdown2\" aria-labelledby=\"dropdown2-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAustin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\techo park vegan.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //single -->\r\n");
      out.write("\t\t<!-- single-related-products -->\r\n");
      out.write("\t\t<div class=\"single-related-products\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h3 class=\"animated wow slideInUp\" data-wow-delay=\".5s\">Related Products</h3>\r\n");
      out.write("\t\t\t\t<p class=\"est animated wow slideInUp\" data-wow-delay=\".5s\">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("\t\t\t\t<div class=\"new-collections-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 new-collections-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"new-collections-grid1 animated wow slideInLeft\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\" class=\"product-image\"><img src=\"images/8.jpg\" alt=\" \" class=\"img-responsive\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image-pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quick View</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"rating\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"single.html\">Running Shoes</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Vel illum qui dolorem eum fugiat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new-collections-grid1-left simpleCart_shelfItem\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><i>$280</i> <span class=\"item_price\">$150</span><a class=\"item_add\" href=\"#\">add to cart </a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 new-collections-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"new-collections-grid1-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new-collections-grid1 animated wow slideInLeft\" data-wow-delay=\".6s\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\" class=\"product-image\"><img src=\"images/6.jpg\" alt=\" \" class=\"img-responsive\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image-pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quick View</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"single.html\">Wall Lamp</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Vel illum qui dolorem eum fugiat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-left simpleCart_shelfItem\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><i>$480</i> <span class=\"item_price\">$400</span><a class=\"item_add\" href=\"#\">add to cart </a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"new-collections-grid1-sub\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new-collections-grid1 animated wow slideInLeft\" data-wow-delay=\".7s\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\" class=\"product-image\"><img src=\"images/9.jpg\" alt=\" \" class=\"img-responsive\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image-pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quick View</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4><a href=\"single.html\">Wall Lamp</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Vel illum qui dolorem eum fugiat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-left simpleCart_shelfItem\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><i>$280</i> <span class=\"item_price\">$150</span><a class=\"item_add\" href=\"#\">add to cart </a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 new-collections-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"new-collections-grid1 animated wow slideInLeft\" data-wow-delay=\".8s\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\" class=\"product-image\"><img src=\"images/11.jpg\" alt=\" \" class=\"img-responsive\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-image-pos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quick View</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"new-collections-grid1-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"rating\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/2.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"rating-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"images/1.png\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"single.html\">Stones Bangles</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Vel illum qui dolorem eum fugiat.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"new-collections-grid1-left simpleCart_shelfItem\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><i>$340</i> <span class=\"item_price\">$257</span><a class=\"item_add\" href=\"#\">add to cart </a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //single-related-products -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- footer -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"footer-grids\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 footer-grid animated wow slideInLeft\"\r\n");
      out.write("\t\t\t\t\tdata-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tDuis aute irure dolor in reprehenderit in voluptate velit esse.<span>Excepteur\r\n");
      out.write("\t\t\t\t\t\t\tsint occaecat cupidatat non proident, sunt in culpa qui officia\r\n");
      out.write("\t\t\t\t\t\t\tdeserunt mollit.</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 footer-grid animated wow slideInLeft\"\r\n");
      out.write("\t\t\t\t\tdata-wow-delay=\".6s\">\r\n");
      out.write("\t\t\t\t\t<h3>Contact Info</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"glyphicon glyphicon-map-marker\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i>1234k Avenue, 4th block, <span>New\r\n");
      out.write("\t\t\t\t\t\t\t\tYork City.</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"glyphicon glyphicon-envelope\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i><a href=\"mailto:info@example.com\">info@example.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><i class=\"glyphicon glyphicon-earphone\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i>+1234 567 567</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 footer-grid animated wow slideInLeft\"\r\n");
      out.write("\t\t\t\t\tdata-wow-delay=\".7s\">\r\n");
      out.write("\t\t\t\t\t<h3>Flickr Posts</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/13.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/14.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/15.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/16.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/13.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/14.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/15.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/16.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/13.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/14.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/15.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/16.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 footer-grid animated wow slideInLeft\"\r\n");
      out.write("\t\t\t\t\tdata-wow-delay=\".8s\">\r\n");
      out.write("\t\t\t\t\t<h3>Blog Posts</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-sub-grids\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-sub-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/9.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-sub-grid-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\">culpa qui officia deserunt</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Posted On 25/3/2016</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-grid-sub-grids\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-sub-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/10.jpg\" alt=\" \"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-responsive\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-sub-grid-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\">Quis autem vel eum iure</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Posted On 25/3/2016</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-logo animated wow slideInUp\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\">Best Store <span>shop anywhere</span></a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"copy-right animated wow slideInUp\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t&copy 2016 Best Store. All rights reserved | Design by <a\r\n");
      out.write("\t\t\t\t\t\thref=\"http://w3layouts.com/\">W3layouts</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //footer -->");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction add(){\r\n");
      out.write("\t\t\t\tvar number=parseInt($(\"#number\").val())+1;\r\n");
      out.write("\t\t\t\t$(\"#number\").val(number);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction reduce(){\r\n");
      out.write("\t\t\t\tvar number=$(\"#number\").val();\r\n");
      out.write("\t\t\t\tif(number>1){\r\n");
      out.write("\t\t\t\t\t$(\"#number\").val(parseInt(number)-1);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /commons/taglibs.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /commons/taglibs.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/taglibs.jsp(5,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /customer/commons/head.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/customer/css/bootstrap.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /customer/commons/head.jsp(17,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/customer/css/style.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /customer/commons/head.jsp(19,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/customer/js/jquery.min.js");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /customer/commons/head.jsp(22,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/customer/js/simpleCart.min.js");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /customer/commons/head.jsp(26,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/customer/css/jquery-ui.css");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /customer/commons/head.jsp(28,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/customer/js/bootstrap-3.1.1.min.js");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent(null);
    // /customer/commons/head.jsp(29,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/customer/css/animate.min.css");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f7.setParent(null);
    // /customer/commons/head.jsp(30,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f7.setValue("/customer/js/wow.min.js");
    int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
    if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
    return false;
  }
}
